#ifndef BEANCAFIINE_CAFIINE_H
#define BEANCAFIINE_CAFIINE_H

#define BYTE_NORMAL 0xFF
#define BYTE_SPECIAL 0xFE
#define BYTE_OPEN 0x00
#define BYTE_READ 0x01
#define BYTE_CLOSE 0x02
#define BYTE_OK 0x03
#define BYTE_SETPOS 0x04
#define BYTE_STATFILE 0x05
#define BYTE_EOF 0x06
#define BYTE_GETPOS 0x07

#endif //BEANCAFIINE_CAFIINE_H
